[project]
name = "asteroids"
version = "0.1.0"
description = "Making a simple Asteroids game as part of my Python learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pygame==2.6.1"]
